const translations = {
  en: {},
  hi: {
    navStay: 'ठहरने की सुविधा', navPilgrimage: 'तीर्थ यात्रा', navLocation: 'स्थान', navContact: 'संपर्क', heroEyebrow: 'बोधगया, बिहार', heroTitle: 'बोधगया के बीचों-बीच एक सरल और अपनापन भरा ठहराव।', heroIntro: 'कालचक्र मैदान के पास परिवार द्वारा चलाया जाने वाला गेस्ट हाउस—इस खास जगह में ठहरने के लिए आरामदायक और सुविधाजनक।', whatsapp: 'व्हाट्सऐप पर संदेश भेजें', contactAnup: 'अनुप हाउस से संपर्क करें', welcoming: 'मेहमानों का स्वागत', since: '2018 से', welcomeEyebrow: 'अनुप हाउस में आपका स्वागत है', welcomeTitle: 'बोधगया में दिन बिताने के बाद आराम करने की एक शांत जगह।', welcomeP1: 'अनुप हाउस में हमारा परिवार 2018 से मेहमानों की देखभाल कर रहा है। यहाँ साफ़ और आरामदायक कमरे, गर्मजोशी से स्वागत और बोधगया के प्रमुख स्थानों के पास सुविधाजनक ठहराव मिलता है।', welcomeP2: 'चाहे आप तीर्थ यात्रा, धर्म शिक्षा, किसी कार्यक्रम या शांति से समय बिताने के लिए आए हों, आपका स्वागत है।', pilgrimageEyebrow: 'तीर्थ यात्रा और धर्म शिक्षा', pilgrimageTitle: 'बोधि वृक्ष और महाबोधि मंदिर के पास।', pilgrimageP1: 'बोधगया दुनिया के सबसे महत्वपूर्ण बौद्ध तीर्थस्थलों में से एक है। पवित्र बोधि वृक्ष वाला महाबोधि मंदिर परिसर यूनेस्को विश्व धरोहर स्थल है।', pilgrimageP2: 'मंदिर आने वाले, वार्षिक मोनलम प्रार्थना सभा में शामिल होने वाले या बोधगया में धर्म शिक्षा और प्रार्थना कार्यक्रमों में भाग लेने वाले मेहमानों के लिए अनुप हाउस एक सुविधाजनक पारिवारिक गेस्ट हाउस है।', pilgrimageP3: 'कार्यक्रम की नई तारीखों और स्थानीय यात्रा की जानकारी के लिए आने से पहले परिवार से संपर्क करें।', stayEyebrow: 'आपका ठहराव', stayTitle: 'आराम के लिए सभी ज़रूरी सुविधाएँ।', roomsTitle: 'आरामदायक कमरे', roomsText: 'आराम से ठहरने के लिए सरल और रोशनी से भरे कमरे।', waterTitle: 'गर्म पानी', waterText: 'आपकी सुविधा के लिए गर्म पानी उपलब्ध है।', wifiText: 'ठहरने के दौरान इंटरनेट से जुड़े रहें।', cctvText: 'अतिरिक्त सुरक्षा के लिए परिसर में सीसीटीवी।', guestEyebrow: 'दोबारा आए मेहमान की बात', guestQuote: '“मैं शशि और उनके परिवार के साथ रहा, बहुत अच्छा समय बिताया और बोधगया में अच्छे दोस्त बनाए। यहाँ दोबारा आकर बहुत खुशी हुई।”', locationEyebrow: 'हमारा स्थान', locationTitle: 'कालचक्र मैदान के पास, बोधगया।', locationText: 'पच्छट्टी में महारानी रोड पर, कालचक्र मैदान के उत्तर में। बोधगया के मंदिर, कैफ़े और तीर्थस्थल भी पास हैं।', googleMaps: 'गूगल मैप्स में खोलें', directionsEyebrow: 'रास्ता', directionsTitle: 'ढूँढना आसान, प्रमुख स्थानों के पास।', directionsText: 'अनुप हाउस महारानी रोड पर, कालचक्र मैदान के उत्तर में है। यहाँ पहुँचने के लिए मानचित्र देखें।', directionsButton: 'रास्ता देखें', contactEyebrow: 'संपर्क करें', contactTitle: 'अनुप हाउस के बारे में कोई सवाल?', contactText: 'सामान्य जानकारी, स्थानीय सलाह या आने की योजना में मदद के लिए सीधे परिवार से संपर्क करें।', whatsappUs: 'व्हाट्सऐप करें', footer: 'बोधगया, भारत में परिवार द्वारा चलाया जाने वाला गेस्ट हाउस।'
  },
  bo: {
    navStay: 'ཞག་སྡོད།', navPilgrimage: 'གནས་མཇལ།', navLocation: 'ས་གནས།', navContact: 'འབྲེལ་གཏུག', heroEyebrow: 'བོད་ག་ཡ། བི་ཧཱར།', heroTitle: 'བོད་ག་ཡའི་ལྟེ་བར་སྟབས་བདེ་དང་དྲོ་བའི་ཞག་སྡོད།', heroIntro: 'ཀ་ལ་ཆཀྲའི་ཐང་གི་ཉེ་འགྲམ་དུ་ཡོད་པའི་ཁྱིམ་ཚང་གི་མགྲོན་ཁང་། དམིགས་བསལ་གྱི་གནས་འདིར་བཞུགས་རིང་བདེ་བའི་གཞི་གནས་ཤིག་ཡིན།', whatsapp: 'WhatsApp ནས་འཕྲིན་སྐུར།', contactAnup: 'ཨ་ནུཔ་ཧའུས་ལ་འབྲེལ་གཏུག', welcoming: 'མགྲོན་པོར་བསུ་བ།', since: '༢༠༡༨ ནས།', welcomeEyebrow: 'ཨ་ནུཔ་ཧའུས་ལ་ཕེབས་བསུ་ཞུ།', welcomeTitle: 'བོད་ག་ཡར་ཉིན་གང་བསྐྱོད་རྗེས་ངལ་གསོ་བྱེད་སའི་ཞི་འཇམ་གྱི་གནས།', welcomeP1: 'ཨ་ནུཔ་ཧའུས་སུ་ང་ཚོའི་ཁྱིམ་ཚང་གིས་༢༠༡༨ ལོ་ནས་མགྲོན་པོ་རྣམས་ལ་ཞབས་ཞུ་ཞུས་ཡོད། ང་ཚོས་གཙང་སྦྲ་དང་བདེ་བའི་ཁང་པ། དྲོ་བའི་ཕེབས་བསུ། དེ་བཞིན་བོད་ག་ཡའི་གལ་ཆེའི་གནས་ཁག་དང་ཉེ་བའི་གཞི་གནས་ཤིག་འབུལ་རྒྱུ་ཡིན།', welcomeP2: 'གནས་མཇལ། ཆོས་ཁྲིད། དུས་སྟོན། ཡང་ན་ངལ་གསོ་བའི་ཆེད་དུ་ཕེབས་ཀྱང་། ང་ཚོས་དགའ་བསུ་ཞུ།', pilgrimageEyebrow: 'གནས་མཇལ་དང་ཆོས་ཁྲིད།', pilgrimageTitle: 'བྱང་ཆུབ་ཤིང་དང་མ་ཧཱ་བོ་དྷི་མཆོད་རྟེན་གྱི་ཉེ་འགྲམ།', pilgrimageP1: 'བོད་ག་ཡ་ནི་འཛམ་གླིང་གི་ནང་པའི་གནས་མཇལ་གལ་ཆེ་ཤོས་ཀྱི་གནས་ཤིག་ཡིན། བྱང་ཆུབ་ཤིང་ཡོད་པའི་མ་ཧཱ་བོ་དྷི་མཆོད་རྟེན་གྱི་ཁུལ་ནི་ UNESCO འཛམ་གླིང་ཤུལ་བཞག་གི་གནས་ཡིན།', pilgrimageP2: 'མཆོད་རྟེན་མཇལ་བ། ལོ་རེའི་སྨོན་ལམ་དུ་ཞུགས་པ། ཡང་ན་བོད་ག་ཡར་འཚོགས་པའི་ཆོས་ཁྲིད་དང་སྨོན་ལམ་གྱི་ལས་རིམ་ལ་ཞུགས་པའི་མགྲོན་པོ་རྣམས་ལ་ཨ་ནུཔ་ཧའུས་ནི་སྟབས་བདེའི་ཁྱིམ་ཚང་གི་གཞི་གནས་ཤིག་ཡིན།', pilgrimageP3: 'ད་ལྟའི་ལས་རིམ་གྱི་ཚེས་གྲངས་དང་ས་གནས་ཀྱི་འགྲུལ་བསྐྱོད་བསླབ་བྱ་ཤེས་འདོད་ན། ཕེབས་པའི་སྔོན་ལ་ཁྱིམ་ཚང་དང་འབྲེལ་གཏུག་གནང་།', stayEyebrow: 'ཁྱེད་ཀྱི་ཞག་སྡོད།', stayTitle: 'བདེ་བའི་དགོས་མཁོ། ལེགས་པར་བདག་སྐྱོང་བྱས་པ།', roomsTitle: 'བདེ་བའི་ཁང་པ།', roomsText: 'ངལ་གསོའི་ཞག་སྡོད་ཆེད་དུ་འོད་འཕྲོ་བའི་སྟབས་བདེའི་ཁང་པ།', waterTitle: 'ཆུ་ཚ་པོ།', waterText: 'ཁྱེད་ཀྱི་བདེ་བའི་ཆེད་དུ་ཆུ་ཚ་པོ་ཡོད།', wifiText: 'ཕྱི་ལོགས་སུ་ཡོད་ཀྱང་འབྲེལ་མཐུད་ཐུབ།', cctvText: 'སེམས་བདེ་བའི་ཆེད་དུ་གནས་ཡུལ་དུ་ CCTV ཡོད།', guestEyebrow: 'ཕྱིར་ལོག་མགྲོན་པོ་ཞིག', guestQuote: '“ང་ཤ་ཤི་དང་ཁོང་གི་ཁྱིམ་ཚང་དང་མཉམ་དུ་བསྡད་པ་ཡིན། དེར་དུས་ཚོད་ཡག་པོ་བསྐྱལ་ཞིང་། བོད་ག་ཡར་གྲོགས་པོ་བཟང་པོ་རྣམས་དང་འཕྲད་བྱུང་། ང་དགའ་པོས་ཕྱིར་ཡང་ལོག་ཡོད།”', locationEyebrow: 'ང་ཚོའི་ས་གནས།', locationTitle: 'ཀ་ལ་ཆཀྲའི་ཐང་གི་ཉེ་འགྲམ། བོད་ག་ཡ།', locationText: 'པཙྪཊིར་ཡོད་པའི་མ་ཧཱ་ར་ནི་ལམ་དུ་སྟབས་བདེར་ཡོད། ཀ་ལ་ཆཀྲའི་ཐང་གི་བྱང་ཕྱོགས་དང་། བོད་ག་ཡའི་མཆོད་རྟེན། ཇ་ཁང་། གནས་མཇལ་གྱི་ས་ཆ་ཁག་དང་ཉེ།', googleMaps: 'Google Maps ནང་ཁ་ཕྱེ།', directionsEyebrow: 'ཁ་ཕྱོགས།', directionsTitle: 'འཚོལ་སླ་བ། གལ་ཆེའི་ས་ཆ་དང་ཉེ།', directionsText: 'ཀ་ལ་ཆཀྲའི་ཐང་གི་བྱང་ཕྱོགས་ཀྱི་མ་ཧཱ་ར་ནི་ལམ་དུ་ཡོད་པའི་ཨ་ནུཔ་ཧའུས་ལ་ཕེབས་པར་ས་ཁྲ་སྤྱོད།', directionsButton: 'ཁ་ཕྱོགས་ལེན།', contactEyebrow: 'འབྲེལ་གཏུག', contactTitle: 'ཨ་ནུཔ་ཧའུས་སྐོར་ལ་དྲི་བ་ཡོད་དམ།', contactText: 'སྤྱིར་བཏང་གི་འདྲི་རྩད། ས་གནས་ཀྱི་ཆ་འཕྲིན། ཡང་ན་ཕེབས་འཆར་གྱི་རོགས་རམ་ཆེད་དུ་ཁྱིམ་ཚང་ལ་ཐད་ཀར་འབྲེལ་གཏུག་གནང་།', whatsappUs: 'WhatsApp གནང་།', footer: 'རྒྱ་གར་བོད་ག་ཡར་ཡོད་པའི་ཁྱིམ་ཚང་གི་མགྲོན་ཁང་།'
  }
};

Object.assign(translations, {
  ja: {
    navStay: '宿泊', navPilgrimage: '巡礼', navLocation: '場所', navContact: 'お問い合わせ', heroEyebrow: 'インド・ビハール州 ボードガヤ', heroTitle: 'ボードガヤ中心部の、シンプルで温かな宿。', heroIntro: 'カラチャクラ・グラウンド近くの家族経営ゲストハウスです。この特別な地で、快適にお過ごしいただけます。', whatsapp: 'WhatsAppでメッセージ', contactAnup: 'アヌップ・ハウスに連絡', welcoming: 'ゲストをお迎えして', since: '2018年から', welcomeEyebrow: 'アヌップ・ハウスへようこそ', welcomeTitle: '一日の終わりに、ほっと落ち着ける場所。', welcomeP1: 'アヌップ・ハウスでは、2018年から家族でゲストをお迎えしています。清潔で快適なお部屋と温かなもてなしをご用意しています。ボードガヤの主な場所にも近く便利です。', welcomeP2: '巡礼、法話、行事への参加、または静かに過ごすためにお越しの皆さまを、心よりお迎えします。', pilgrimageEyebrow: '巡礼と法話', pilgrimageTitle: '菩提樹とマハーボディ寺院の近く。', pilgrimageP1: 'ボードガヤは世界有数の仏教巡礼地です。聖なる菩提樹があるマハーボディ寺院は、ユネスコ世界遺産に登録されています。', pilgrimageP2: '寺院を訪れる方、毎年のモンラム祈願祭に参加する方、ボードガヤで行われる法話や祈りの行事に参加する方に便利な家族経営の宿です。', pilgrimageP3: '最新の日程や現地の交通情報は、ご到着前に家族までお問い合わせください。', stayEyebrow: 'ご滞在', stayTitle: '快適な滞在に必要な設備を揃えています。', roomsTitle: '快適なお部屋', roomsText: 'ゆっくり休める、明るくシンプルなお部屋です。', waterTitle: '温水', waterText: '温水をご利用いただけます。', wifiText: 'ご滞在中もインターネットをご利用いただけます。', cctvText: '安心してお過ごしいただけるよう、敷地内にCCTVを設置しています。', guestEyebrow: 'リピーターの声', guestQuote: '「シャシとご家族のもとで、とても楽しい時間を過ごしました。親しい友人になり、また泊まりに来るようになりました。」', locationEyebrow: 'アクセス', locationTitle: 'ボードガヤ、カラチャクラ・グラウンド近く。', locationText: 'パッチャッティのマハラニ・ロード、カラチャクラ・グラウンドのすぐ北にあります。寺院、カフェ、巡礼地にも近く便利です。', googleMaps: 'Googleマップで開く', directionsEyebrow: '道順', directionsTitle: '見つけやすく、主な場所にも近い。', directionsText: 'アヌップ・ハウスは、カラチャクラ・グラウンド北側のマハラニ・ロードにあります。地図をご利用ください。', directionsButton: '道順を見る', contactEyebrow: 'お問い合わせ', contactTitle: 'アヌップ・ハウスについてご質問ですか？', contactText: '一般的なご質問、現地情報、到着のご相談は、家族に直接ご連絡ください。', whatsappUs: 'WhatsAppで連絡', footer: 'インド・ボードガヤの家族経営ゲストハウス。'
  },
  th: {
    navStay: 'ที่พัก', navPilgrimage: 'แสวงบุญ', navLocation: 'ที่ตั้ง', navContact: 'ติดต่อ', heroEyebrow: 'พุทธคยา รัฐพิหาร', heroTitle: 'ที่พักเรียบง่ายและอบอุ่น ใจกลางพุทธคยา', heroIntro: 'เกสต์เฮาส์ที่ดูแลโดยครอบครัว ใกล้ลานกาลจักร สะดวกและสบายสำหรับการพักในสถานที่พิเศษแห่งนี้', whatsapp: 'ส่งข้อความทาง WhatsApp', contactAnup: 'ติดต่อ Anup House', welcoming: 'ต้อนรับผู้เข้าพัก', since: 'ตั้งแต่ปี 2018', welcomeEyebrow: 'ยินดีต้อนรับสู่ Anup House', welcomeTitle: 'ที่พักสงบ ๆ หลังจากใช้เวลาทั้งวันในพุทธคยา', welcomeP1: 'ครอบครัวของเราดูแลผู้เข้าพักที่ Anup House มาตั้งแต่ปี 2018 เรามีห้องพักสะอาดและสบาย พร้อมการต้อนรับอย่างอบอุ่น และอยู่ใกล้สถานที่สำคัญของพุทธคยา', welcomeP2: 'ไม่ว่าคุณจะมาแสวงบุญ ฟังธรรม เข้าร่วมงาน หรือพักผ่อนอย่างสงบ เรายินดีต้อนรับคุณ', pilgrimageEyebrow: 'แสวงบุญและฟังธรรม', pilgrimageTitle: 'ใกล้ต้นพระศรีมหาโพธิ์และวัดมหาโพธิ์', pilgrimageP1: 'พุทธคยาเป็นหนึ่งในสถานที่แสวงบุญทางพุทธศาสนาที่สำคัญที่สุดของโลก วัดมหาโพธิ์และต้นพระศรีมหาโพธิ์อันศักดิ์สิทธิ์ได้รับการขึ้นทะเบียนเป็นมรดกโลกโดยยูเนสโก', pilgrimageP2: 'Anup House เป็นเกสต์เฮาส์ที่ดูแลโดยครอบครัว เหมาะสำหรับผู้มาเยือนวัด ผู้ร่วมงานสวดมนต์มนลัมประจำปี และผู้เข้าร่วมการสอนธรรมะหรือกิจกรรมสวดมนต์ในพุทธคยา', pilgrimageP3: 'โปรดติดต่อครอบครัวก่อนเดินทาง เพื่อสอบถามกำหนดการล่าสุดและข้อมูลการเดินทางในพื้นที่', stayEyebrow: 'การเข้าพักของคุณ', stayTitle: 'สิ่งอำนวยความสะดวกที่จำเป็นสำหรับการพักอย่างสบาย', roomsTitle: 'ห้องพักสะดวกสบาย', roomsText: 'ห้องพักเรียบง่าย สว่าง และเหมาะสำหรับการพักผ่อน', waterTitle: 'น้ำร้อน', waterText: 'มีน้ำร้อนให้บริการ', wifiText: 'ใช้อินเทอร์เน็ตได้ตลอดการเข้าพัก', cctvText: 'มีกล้องวงจรปิดในที่พักเพื่อความอุ่นใจ', guestEyebrow: 'เสียงจากผู้เข้าพักที่กลับมาอีกครั้ง', guestQuote: '“ฉันพักกับชาชิและครอบครัว มีช่วงเวลาที่ดีมาก เรากลายเป็นเพื่อนกัน และฉันก็กลับมาพักอีก”', locationEyebrow: 'ที่ตั้ง', locationTitle: 'ใกล้ลานกาลจักร พุทธคยา', locationText: 'ตั้งอยู่บนถนนมหารานี ในปัจฉัตตี ทางเหนือของลานกาลจักร ใกล้วัด คาเฟ่ และสถานที่แสวงบุญในพุทธคยา', googleMaps: 'เปิดใน Google Maps', directionsEyebrow: 'เส้นทาง', directionsTitle: 'หาได้ง่าย ใกล้สถานที่สำคัญ', directionsText: 'Anup House อยู่บนถนนมหารานี ทางเหนือของลานกาลจักร ใช้แผนที่เพื่อดูเส้นทาง', directionsButton: 'ดูเส้นทาง', contactEyebrow: 'ติดต่อเรา', contactTitle: 'มีคำถามเกี่ยวกับ Anup House?', contactText: 'หากต้องการสอบถามข้อมูลทั่วไป ข้อมูลท้องถิ่น หรือวางแผนการเดินทาง โปรดติดต่อครอบครัวโดยตรง', whatsappUs: 'ติดต่อทาง WhatsApp', footer: 'เกสต์เฮาส์ที่ดูแลโดยครอบครัวในพุทธคยา ประเทศอินเดีย'
  }
});

Object.assign(translations, {
  vi: {
    navStay: 'Lưu trú', navPilgrimage: 'Hành hương', navLocation: 'Vị trí', navContact: 'Liên hệ', heroEyebrow: 'Bodhgaya, Bihar', heroTitle: 'Chỗ nghỉ giản dị và thân thiện giữa lòng Bodhgaya.', heroIntro: 'Nhà nghỉ do gia đình quản lý, gần sân Kalachakra. Một nơi thoải mái và thuận tiện để lưu trú tại vùng đất đặc biệt này.', whatsapp: 'Nhắn tin qua WhatsApp', contactAnup: 'Liên hệ Anup House', welcoming: 'Đón tiếp du khách', since: 'từ năm 2018', welcomeEyebrow: 'Chào mừng đến Anup House', welcomeTitle: 'Nơi yên bình để nghỉ ngơi sau một ngày ở Bodhgaya.', welcomeP1: 'Gia đình chúng tôi đã đón tiếp du khách tại Anup House từ năm 2018. Phòng nghỉ sạch sẽ, thoải mái, không khí thân thiện và vị trí thuận tiện gần những địa điểm chính của Bodhgaya.', welcomeP2: 'Dù bạn đến để hành hương, nghe giảng pháp, tham dự sự kiện hay nghỉ ngơi yên tĩnh, chúng tôi luôn vui mừng chào đón bạn.', pilgrimageEyebrow: 'Hành hương và giảng pháp', pilgrimageTitle: 'Gần Cây Bồ-đề và chùa Mahabodhi.', pilgrimageP1: 'Bodhgaya là một trong những địa điểm hành hương Phật giáo quan trọng nhất thế giới. Chùa Mahabodhi và Cây Bồ-đề linh thiêng đã được UNESCO công nhận là Di sản Thế giới.', pilgrimageP2: 'Anup House là nhà nghỉ gia đình thuận tiện cho khách viếng chùa, tham dự lễ cầu nguyện Monlam hằng năm hoặc các buổi giảng pháp và cầu nguyện tại Bodhgaya.', pilgrimageP3: 'Vui lòng liên hệ gia đình trước khi đến để biết lịch mới nhất và thông tin đi lại tại địa phương.', stayEyebrow: 'Kỳ lưu trú của bạn', stayTitle: 'Đầy đủ tiện nghi thiết yếu cho một kỳ nghỉ thoải mái.', roomsTitle: 'Phòng thoải mái', roomsText: 'Phòng đơn giản, sáng sủa để bạn nghỉ ngơi.', waterTitle: 'Nước nóng', waterText: 'Có nước nóng phục vụ khách.', wifiText: 'Có Wi-Fi trong thời gian lưu trú.', cctvText: 'Có camera an ninh trong khuôn viên để bạn yên tâm.', guestEyebrow: 'Chia sẻ từ khách quay lại', guestQuote: '“Tôi đã có khoảng thời gian tuyệt vời cùng Shashi và gia đình. Chúng tôi trở thành những người bạn tốt, và tôi đã quay lại lưu trú.”', locationEyebrow: 'Vị trí', locationTitle: 'Gần sân Kalachakra, Bodhgaya.', locationText: 'Nằm trên đường Maharani ở Pachhatti, phía bắc sân Kalachakra, gần các ngôi chùa, quán cà phê và điểm hành hương ở Bodhgaya.', googleMaps: 'Mở bằng Google Maps', directionsEyebrow: 'Chỉ đường', directionsTitle: 'Dễ tìm, gần các địa điểm chính.', directionsText: 'Anup House nằm trên đường Maharani, phía bắc sân Kalachakra. Hãy dùng bản đồ để xem đường đi.', directionsButton: 'Xem chỉ đường', contactEyebrow: 'Liên hệ', contactTitle: 'Bạn có câu hỏi về Anup House?', contactText: 'Để hỏi thông tin chung, thông tin địa phương hoặc được hỗ trợ lên kế hoạch đến nơi, vui lòng liên hệ trực tiếp với gia đình.', whatsappUs: 'Liên hệ qua WhatsApp', footer: 'Nhà nghỉ do gia đình quản lý tại Bodhgaya, Ấn Độ.'
  },
  ko: {
    navStay: '숙박', navPilgrimage: '순례', navLocation: '위치', navContact: '문의', heroEyebrow: '인도 비하르주 보드가야', heroTitle: '보드가야 중심의 소박하고 따뜻한 숙소.', heroIntro: '칼라차크라 광장 근처에 있는 가족 운영 게스트하우스입니다. 이 특별한 곳에서 편안하고 편리하게 머물 수 있습니다.', whatsapp: 'WhatsApp으로 메시지', contactAnup: '아눕 하우스에 문의', welcoming: '손님을 맞이해 온', since: '2018년부터', welcomeEyebrow: '아눕 하우스에 오신 것을 환영합니다', welcomeTitle: '보드가야에서 하루를 보낸 뒤 편안히 쉴 수 있는 곳.', welcomeP1: '아눕 하우스는 2018년부터 가족이 함께 손님을 맞이해 왔습니다. 깨끗하고 편안한 객실과 따뜻한 환대를 제공하며, 보드가야의 주요 명소와도 가깝습니다.', welcomeP2: '순례, 법회, 행사 또는 조용한 휴식을 위해 오시는 모든 분을 기쁘게 맞이합니다.', pilgrimageEyebrow: '순례와 법회', pilgrimageTitle: '보리수와 마하보디 사원 가까이.', pilgrimageP1: '보드가야는 세계에서 가장 중요한 불교 순례지 중 하나입니다. 성스러운 보리수와 마하보디 사원은 유네스코 세계유산으로 지정되어 있습니다.', pilgrimageP2: '아눕 하우스는 사원을 방문하거나 매년 열리는 몬람 기도회, 법회와 기도 프로그램에 참여하는 분들에게 편리한 가족 운영 숙소입니다.', pilgrimageP3: '최신 일정과 현지 교통 정보는 도착 전에 가족에게 문의해 주세요.', stayEyebrow: '숙박 안내', stayTitle: '편안한 숙박에 필요한 기본 시설을 갖추고 있습니다.', roomsTitle: '편안한 객실', roomsText: '밝고 소박하며 편안히 쉴 수 있는 객실입니다.', waterTitle: '온수', waterText: '온수를 이용하실 수 있습니다.', wifiText: '숙박 중 Wi-Fi를 이용하실 수 있습니다.', cctvText: '안심하고 머무실 수 있도록 숙소에 CCTV가 설치되어 있습니다.', guestEyebrow: '다시 찾은 손님의 이야기', guestQuote: '“샤시와 가족과 함께 정말 좋은 시간을 보냈습니다. 서로 좋은 친구가 되었고, 다시 머물러 왔습니다.”', locationEyebrow: '위치', locationTitle: '보드가야 칼라차크라 광장 근처.', locationText: '파차티의 마하라니 로드, 칼라차크라 광장 북쪽에 있습니다. 보드가야의 사원, 카페, 순례지도 가깝습니다.', googleMaps: 'Google 지도에서 열기', directionsEyebrow: '길 안내', directionsTitle: '찾기 쉽고 주요 장소와 가깝습니다.', directionsText: '아눕 하우스는 칼라차크라 광장 북쪽 마하라니 로드에 있습니다. 지도를 이용해 주세요.', directionsButton: '길찾기', contactEyebrow: '문의하기', contactTitle: '아눕 하우스에 대해 궁금하신가요?', contactText: '일반 문의, 현지 정보 또는 도착 계획에 도움이 필요하시면 가족에게 직접 연락해 주세요.', whatsappUs: 'WhatsApp으로 연락', footer: '인도 보드가야의 가족 운영 게스트하우스.'
  }
});

Object.assign(translations, {
  'zh-CN': {
    navStay: '住宿', navPilgrimage: '朝圣', navLocation: '位置', navContact: '联系', heroEyebrow: '印度比哈尔邦菩提迦耶', heroTitle: '菩提迦耶中心，一处简单温馨的住处。', heroIntro: '由一家人经营的旅馆，靠近时轮金刚法会场地。在这片特别的土地上，为您提供舒适便利的落脚处。', whatsapp: '通过 WhatsApp 发消息', contactAnup: '联系 Anup House', welcoming: '欢迎宾客', since: '始于 2018 年', welcomeEyebrow: '欢迎来到 Anup House', welcomeTitle: '在菩提迦耶度过一天后，可以安心休息的地方。', welcomeP1: '自 2018 年以来，我们一家人一直在 Anup House 接待宾客。这里有干净舒适的房间、热情的招待，而且靠近菩提迦耶的主要地点。', welcomeP2: '无论您是来朝圣、听闻佛法、参加活动，还是安静休息，我们都热情欢迎您。', pilgrimageEyebrow: '朝圣与佛法开示', pilgrimageTitle: '靠近菩提树和摩诃菩提寺。', pilgrimageP1: '菩提迦耶是世界上最重要的佛教朝圣地之一。摩诃菩提寺和神圣的菩提树已被列入联合国教科文组织世界遗产名录。', pilgrimageP2: '无论是前往寺院、参加年度祈愿法会（Monlam），还是参加菩提迦耶的佛法开示和祈祷活动，Anup House 都是方便的家庭旅馆。', pilgrimageP3: '如需了解最新活动日期和当地交通信息，请在抵达前联系这家人。', stayEyebrow: '您的住宿', stayTitle: '舒适住宿所需的基本设施。', roomsTitle: '舒适客房', roomsText: '简单明亮的房间，让您好好休息。', waterTitle: '热水', waterText: '提供热水。', wifiText: '住宿期间提供 Wi-Fi。', cctvText: '旅馆内装有监控摄像头，让您住得更安心。', guestEyebrow: '回头客的话', guestQuote: '“我和 Shashi 一家住在一起，度过了非常愉快的时光。我们成了好朋友，我也再次回来住宿。”', locationEyebrow: '位置', locationTitle: '靠近菩提迦耶时轮金刚法会场地。', locationText: '位于 Pachhatti 的 Maharani Road，时轮金刚法会场地北侧，靠近菩提迦耶的寺院、咖啡馆和朝圣地。', googleMaps: '在 Google 地图中打开', directionsEyebrow: '路线', directionsTitle: '容易找到，靠近主要地点。', directionsText: 'Anup House 位于时轮金刚法会场地北侧的 Maharani Road。请使用地图查看路线。', directionsButton: '查看路线', contactEyebrow: '联系我们', contactTitle: '想了解 Anup House？', contactText: '如需一般信息、当地建议或抵达帮助，请直接联系这家人。', whatsappUs: '通过 WhatsApp 联系', footer: '印度菩提迦耶的家庭旅馆。'
  },
  'zh-TW': {
    navStay: '住宿', navPilgrimage: '朝聖', navLocation: '位置', navContact: '聯絡', heroEyebrow: '印度比哈爾邦菩提迦耶', heroTitle: '菩提迦耶市中心，一處簡單又溫馨的住處。', heroIntro: '由一家人經營的民宿，鄰近時輪金剛法會場地。在這片特別的土地上，提供舒適便利的住宿。', whatsapp: '透過 WhatsApp 傳訊息', contactAnup: '聯絡 Anup House', welcoming: '歡迎旅客', since: '自 2018 年起', welcomeEyebrow: '歡迎來到 Anup House', welcomeTitle: '在菩提迦耶度過一天後，可以安心休息的地方。', welcomeP1: '自 2018 年起，我們一家人一直在 Anup House 接待旅客。這裡有乾淨舒適的房間、親切的招待，而且鄰近菩提迦耶的主要地點。', welcomeP2: '無論您是來朝聖、聽聞佛法、參加活動，或想安靜休息，我們都很歡迎您。', pilgrimageEyebrow: '朝聖與佛法開示', pilgrimageTitle: '鄰近菩提樹與摩訶菩提寺。', pilgrimageP1: '菩提迦耶是世界上最重要的佛教朝聖地之一。摩訶菩提寺與神聖的菩提樹已列入聯合國教科文組織世界遺產。', pilgrimageP2: '無論是前往寺院、參加每年的祈願法會（Monlam），或參加菩提迦耶的佛法開示與祈禱活動，Anup House 都是方便的家庭民宿。', pilgrimageP3: '如需最新活動日期與當地交通資訊，請在抵達前聯絡這家人。', stayEyebrow: '您的住宿', stayTitle: '舒適住宿所需的基本設施。', roomsTitle: '舒適客房', roomsText: '簡單明亮的房間，讓您好好休息。', waterTitle: '熱水', waterText: '提供熱水。', wifiText: '住宿期間提供 Wi-Fi。', cctvText: '民宿內裝有監視器，讓您住得更安心。', guestEyebrow: '回訪旅客的話', guestQuote: '「我和 Shashi 一家人共度了非常愉快的時光。我們成為好朋友，我也再次回來住宿。」', locationEyebrow: '位置', locationTitle: '鄰近菩提迦耶時輪金剛法會場地。', locationText: '位於 Pachhatti 的 Maharani Road、時輪金剛法會場地北側，鄰近菩提迦耶的寺院、咖啡館與朝聖地。', googleMaps: '在 Google 地圖中開啟', directionsEyebrow: '路線', directionsTitle: '容易找到，鄰近主要地點。', directionsText: 'Anup House 位於時輪金剛法會場地北側的 Maharani Road。請使用地圖查看路線。', directionsButton: '查看路線', contactEyebrow: '聯絡我們', contactTitle: '想了解 Anup House？', contactText: '如需一般資訊、當地建議或抵達協助，請直接聯絡這家人。', whatsappUs: '透過 WhatsApp 聯絡', footer: '印度菩提迦耶的家庭民宿。'
  },
  'yue-HK': {
    navStay: '住宿', navPilgrimage: '朝聖', navLocation: '位置', navContact: '聯絡', heroEyebrow: '印度比哈爾邦菩提迦耶', heroTitle: '菩提迦耶中心，一個簡單又親切嘅住宿地方。', heroIntro: 'Anup House 係一間家庭經營嘅賓館，鄰近時輪金剛法會場地，方便你喺呢個特別嘅地方舒適入住。', whatsapp: '用 WhatsApp 傳訊息', contactAnup: '聯絡 Anup House', welcoming: '歡迎旅客', since: '由 2018 年開始', welcomeEyebrow: '歡迎嚟到 Anup House', welcomeTitle: '喺菩提迦耶過完一日之後，可以安心休息嘅地方。', welcomeP1: '我哋一家人由 2018 年開始喺 Anup House 接待旅客。呢度有乾淨舒適嘅房間、親切嘅招待，而且鄰近菩提迦耶嘅主要地點。', welcomeP2: '無論你係嚟朝聖、聽法、參加活動，定係想安靜休息，我哋都好歡迎你。', pilgrimageEyebrow: '朝聖同佛法開示', pilgrimageTitle: '鄰近菩提樹同摩訶菩提寺。', pilgrimageP1: '菩提迦耶係世界上最重要嘅佛教朝聖地之一。摩訶菩提寺同神聖嘅菩提樹已列入聯合國教科文組織世界遺產。', pilgrimageP2: '無論係去寺院、參加每年嘅祈願法會（Monlam），定係參加菩提迦耶嘅佛法開示同祈禱活動，Anup House 都係一間方便嘅家庭賓館。', pilgrimageP3: '想知道最新活動日期同當地交通資料，請喺到埗之前聯絡我哋一家人。', stayEyebrow: '住宿', stayTitle: '舒適住宿所需嘅基本設施。', roomsTitle: '舒適客房', roomsText: '簡單明亮嘅房間，俾你好好休息。', waterTitle: '熱水', waterText: '有熱水供應。', wifiText: '住宿期間有 Wi-Fi。', cctvText: '賓館內裝有閉路電視，令你住得更安心。', guestEyebrow: '回訪旅客分享', guestQuote: '「我同 Shashi 一家人度過咗非常愉快嘅時光。我哋成為咗好朋友，而我亦再次返嚟住宿。」', locationEyebrow: '位置', locationTitle: '鄰近菩提迦耶時輪金剛法會場地。', locationText: '位於 Pachhatti 嘅 Maharani Road、時輪金剛法會場地北面，鄰近菩提迦耶嘅寺院、咖啡店同朝聖地。', googleMaps: '喺 Google 地圖開啟', directionsEyebrow: '路線', directionsTitle: '容易搵，鄰近主要地點。', directionsText: 'Anup House 位於時輪金剛法會場地北面嘅 Maharani Road。請用地圖查看路線。', directionsButton: '查看路線', contactEyebrow: '聯絡我哋', contactTitle: '想了解 Anup House？', contactText: '如果想問一般資料、當地建議或者到埗安排，請直接聯絡我哋一家人。', whatsappUs: '用 WhatsApp 聯絡', footer: '印度菩提迦耶嘅家庭賓館。'
  }
});

Object.assign(translations, {
  my: {
    navStay: 'တည်းခိုရန်', navPilgrimage: 'ဘုရားဖူး', navLocation: 'တည်နေရာ', navContact: 'ဆက်သွယ်ရန်', heroEyebrow: 'ဗုဒ္ဓဂယာ၊ ဘီဟာပြည်နယ်', heroTitle: 'ဗုဒ္ဓဂယာမြို့လယ်ရှိ ရိုးရှင်းနွေးထွေးသော တည်းခိုရာ။', heroIntro: 'ကာလစကြာကွင်းအနီး မိသားစုစီမံခန့်ခွဲသည့် ဧည့်ရိပ်သာဖြစ်ပြီး ဤထူးခြားသောနေရာတွင် သက်သောင့်သက်သာ တည်းခိုနိုင်ပါသည်။', whatsapp: 'WhatsApp မှ စာပို့ရန်', contactAnup: 'Anup House ကို ဆက်သွယ်ရန်', welcoming: 'ဧည့်သည်များကို ကြိုဆိုလာခဲ့သည်', since: '၂၀၁၈ ခုနှစ်မှစ၍', welcomeEyebrow: 'Anup House မှ ကြိုဆိုပါသည်', welcomeTitle: 'ဗုဒ္ဓဂယာတွင် တစ်နေ့တာကုန်ဆုံးပြီးနောက် အေးချမ်းစွာ အနားယူနိုင်သောနေရာ။', welcomeP1: 'ကျွန်ုပ်တို့မိသားစုသည် ၂၀၁၈ ခုနှစ်မှစ၍ Anup House တွင် ဧည့်သည်များကို ကြိုဆိုစောင့်ရှောက်လာခဲ့ပါသည်။ သန့်ရှင်းသက်သောင့်သက်သာရှိသော အခန်းများ၊ နွေးထွေးသောဧည့်ခံမှုနှင့် ဗုဒ္ဓဂယာ၏ အဓိကနေရာများအနီး အဆင်ပြေသောတည်နေရာ ရှိပါသည်။', welcomeP2: 'ဘုရားဖူးရန်၊ တရားနာရန်၊ ပွဲတက်ရန် သို့မဟုတ် အေးချမ်းစွာ အနားယူရန် လာရောက်သူအားလုံးကို ဝမ်းမြောက်စွာ ကြိုဆိုပါသည်။', pilgrimageEyebrow: 'ဘုရားဖူးနှင့် တရားတော်', pilgrimageTitle: 'ဗောဓိပင်နှင့် မဟာဗောဓိဘုရားကျောင်းအနီး။', pilgrimageP1: 'ဗုဒ္ဓဂယာသည် ကမ္ဘာ့အရေးအကြီးဆုံး ဗုဒ္ဓဘာသာဘုရားဖူးနေရာများထဲမှ တစ်ခုဖြစ်သည်။ မဟာဗောဓိဘုရားကျောင်းနှင့် မြတ်စွာသောဗောဓိပင်ကို ယူနက်စကို ကမ္ဘာ့အမွေအနှစ်အဖြစ် သတ်မှတ်ထားပါသည်။', pilgrimageP2: 'ဘုရားကျောင်းသို့ သွားရောက်သူများ၊ နှစ်စဉ် မိုန်လမ်ဆုတောင်းပွဲတက်ရောက်သူများနှင့် ဗုဒ္ဓဂယာရှိ တရားပွဲနှင့် ဆုတောင်းပွဲများတက်ရောက်သူများအတွက် Anup House သည် အဆင်ပြေသော မိသားစုဧည့်ရိပ်သာဖြစ်ပါသည်။', pilgrimageP3: 'နောက်ဆုံးပွဲရက်များနှင့် ဒေသတွင်းသွားလာရေးအချက်အလက်များအတွက် မရောက်မီ မိသားစုထံ ဆက်သွယ်ပါ။', stayEyebrow: 'သင်၏တည်းခိုမှု', stayTitle: 'သက်သောင့်သက်သာ တည်းခိုရန် လိုအပ်သော အခြေခံပစ္စည်းများ။', roomsTitle: 'သက်သောင့်သက်သာ အခန်းများ', roomsText: 'အနားယူရန် ရိုးရှင်းပြီး အလင်းရောင်ကောင်းသော အခန်းများ။', waterTitle: 'ရေနွေး', waterText: 'ရေနွေး ရရှိပါသည်။', wifiText: 'တည်းခိုစဉ် Wi-Fi အသုံးပြုနိုင်ပါသည်။', cctvText: 'စိတ်ချမ်းသာစွာ တည်းခိုနိုင်ရန် CCTV တပ်ဆင်ထားပါသည်။', guestEyebrow: 'ပြန်လာသောဧည့်သည်၏စကား', guestQuote: '“Shashi နဲ့ သူ့မိသားစုဆီမှာ နေခဲ့ရတာ အရမ်းပျော်ခဲ့ပါတယ်။ ကျွန်တော်တို့ မိတ်ဆွေကောင်းတွေဖြစ်လာပြီး ထပ်မံတည်းခိုဖို့ ပြန်လာခဲ့ပါတယ်။”', locationEyebrow: 'တည်နေရာ', locationTitle: 'ဗုဒ္ဓဂယာ ကာလစကြာကွင်းအနီး။', locationText: 'Pachhatti ရှိ Maharani Road ပေါ်၊ ကာလစကြာကွင်း၏ မြောက်ဘက်တွင်ရှိပြီး ဗုဒ္ဓဂယာရှိ ဘုရားကျောင်းများ၊ ကော်ဖီဆိုင်များနှင့် ဘုရားဖူးနေရာများအနီး ဖြစ်ပါသည်။', googleMaps: 'Google Maps တွင် ဖွင့်ရန်', directionsEyebrow: 'လမ်းညွှန်', directionsTitle: 'ရှာရလွယ်ပြီး အဓိကနေရာများနှင့် နီးပါသည်။', directionsText: 'Anup House သည် ကာလစကြာကွင်းမြောက်ဘက် Maharani Road ပေါ်တွင် ရှိပါသည်။ လမ်းကြောင်းကြည့်ရန် မြေပုံကို အသုံးပြုပါ။', directionsButton: 'လမ်းကြောင်းကြည့်ရန်', contactEyebrow: 'ဆက်သွယ်ရန်', contactTitle: 'Anup House အကြောင်း မေးလိုပါသလား။', contactText: 'အထွေထွေအချက်အလက်၊ ဒေသတွင်းအကြံပြုချက် သို့မဟုတ် ရောက်ရှိရေးအကူအညီအတွက် မိသားစုထံ တိုက်ရိုက်ဆက်သွယ်ပါ။', whatsappUs: 'WhatsApp မှ ဆက်သွယ်ရန်', footer: 'အိန္ဒိယနိုင်ငံ ဗုဒ္ဓဂယာရှိ မိသားစုဧည့်ရိပ်သာ။'
  },
  lo: {
    navStay: 'ທີ່ພັກ', navPilgrimage: 'ຈາລິກບຸນ', navLocation: 'ທີ່ຕັ້ງ', navContact: 'ຕິດຕໍ່', heroEyebrow: 'ພຸດທະຄະຍາ, ລັດພິຫາ', heroTitle: 'ທີ່ພັກທີ່ລຽບງ່າຍ ແລະ ອົບອຸ່ນໃຈກາງພຸດທະຄະຍາ.', heroIntro: 'ເຮືອນພັກທີ່ຄອບຄົວເປັນຜູ້ດູແລ ຢູ່ໃກ້ສະໜາມ Kalachakra. ສະດວກ ແລະ ສະບາຍສຳລັບການພັກໃນສະຖານທີ່ພິເສດແຫ່ງນີ້.', whatsapp: 'ສົ່ງຂໍ້ຄວາມທາງ WhatsApp', contactAnup: 'ຕິດຕໍ່ Anup House', welcoming: 'ຕ້ອນຮັບແຂກ', since: 'ຕັ້ງແຕ່ປີ 2018', welcomeEyebrow: 'ຍິນດີຕ້ອນຮັບສູ່ Anup House', welcomeTitle: 'ບ່ອນພັກທີ່ສະຫງົບ ຫຼັງຈາກໃຊ້ເວລາໜຶ່ງມື້ໃນພຸດທະຄະຍາ.', welcomeP1: 'ຄອບຄົວຂອງພວກເຮົາໄດ້ຕ້ອນຮັບແຂກຢູ່ Anup House ຕັ້ງແຕ່ປີ 2018. ພວກເຮົາມີຫ້ອງທີ່ສະອາດ ແລະ ສະບາຍ, ການຕ້ອນຮັບທີ່ອົບອຸ່ນ ແລະ ຢູ່ໃກ້ສະຖານທີ່ສຳຄັນຂອງພຸດທະຄະຍາ.', welcomeP2: 'ບໍ່ວ່າທ່ານຈະມາຈາລິກບຸນ, ຟັງທຳ, ຮ່ວມງານ ຫຼື ພັກຜ່ອນຢ່າງສະຫງົບ, ພວກເຮົາຍິນດີຕ້ອນຮັບ.', pilgrimageEyebrow: 'ຈາລິກບຸນ ແລະ ຟັງທຳ', pilgrimageTitle: 'ໃກ້ຕົ້ນພະສີມະຫາໂພ ແລະ ວັດມະຫາໂພທິ.', pilgrimageP1: 'ພຸດທະຄະຍາແມ່ນໜຶ່ງໃນສະຖານທີ່ຈາລິກບຸນທາງພຸດທະສາສະໜາທີ່ສຳຄັນທີ່ສຸດໃນໂລກ. ວັດມະຫາໂພທິ ແລະ ຕົ້ນພະສີມະຫາໂພອັນສັກສິດ ໄດ້ຮັບການຂຶ້ນທະບຽນເປັນມໍລະດົກໂລກຂອງ UNESCO.', pilgrimageP2: 'Anup House ເປັນເຮືອນພັກຄອບຄົວທີ່ສະດວກ ສຳລັບຜູ້ໄປວັດ, ຮ່ວມງານສວດມົນ Monlam ປະຈຳປີ ຫຼື ຮ່ວມການສອນທຳ ແລະ ກິດຈະກຳສວດມົນໃນພຸດທະຄະຍາ.', pilgrimageP3: 'ກະລຸນາຕິດຕໍ່ຄອບຄົວກ່ອນເດີນທາງ ເພື່ອສອບຖາມກຳນົດການຫຼ້າສຸດ ແລະ ຂໍ້ມູນການເດີນທາງໃນພື້ນທີ່.', stayEyebrow: 'ການພັກຂອງທ່ານ', stayTitle: 'ສິ່ງອຳນວຍຄວາມສະດວກພື້ນຖານສຳລັບການພັກຢ່າງສະບາຍ.', roomsTitle: 'ຫ້ອງພັກສະບາຍ', roomsText: 'ຫ້ອງພັກລຽບງ່າຍ ແລະ ສະຫວ່າງ ສຳລັບການພັກຜ່ອນ.', waterTitle: 'ນ້ຳຮ້ອນ', waterText: 'ມີນ້ຳຮ້ອນໃຫ້ບໍລິການ.', wifiText: 'ມີ Wi-Fi ໃນລະຫວ່າງການພັກ.', cctvText: 'ມີກ້ອງ CCTV ໃນທີ່ພັກເພື່ອຄວາມສະບາຍໃຈ.', guestEyebrow: 'ສຽງຈາກແຂກທີ່ກັບມາພັກອີກ', guestQuote: '“ຂ້ອຍໄດ້ພັກກັບ Shashi ແລະ ຄອບຄົວ ແລະ ມີເວລາທີ່ດີຫຼາຍ. ພວກເຮົາກາຍເປັນໝູ່ທີ່ດີ ແລະ ຂ້ອຍໄດ້ກັບມາພັກອີກ.”', locationEyebrow: 'ທີ່ຕັ້ງ', locationTitle: 'ໃກ້ສະໜາມ Kalachakra, ພຸດທະຄະຍາ.', locationText: 'ຕັ້ງຢູ່ຖະໜົນ Maharani ໃນ Pachhatti, ທາງເໜືອຂອງສະໜາມ Kalachakra ແລະ ໃກ້ກັບວັດ, ຮ້ານກາເຟ ແລະ ສະຖານທີ່ຈາລິກບຸນໃນພຸດທະຄະຍາ.', googleMaps: 'ເປີດໃນ Google Maps', directionsEyebrow: 'ເສັ້ນທາງ', directionsTitle: 'ຊອກຫາງ່າຍ ແລະ ໃກ້ສະຖານທີ່ສຳຄັນ.', directionsText: 'Anup House ຕັ້ງຢູ່ຖະໜົນ Maharani ທາງເໜືອຂອງສະໜາມ Kalachakra. ກະລຸນາໃຊ້ແຜນທີ່ເພື່ອເບິ່ງເສັ້ນທາງ.', directionsButton: 'ເບິ່ງເສັ້ນທາງ', contactEyebrow: 'ຕິດຕໍ່ພວກເຮົາ', contactTitle: 'ມີຄຳຖາມກ່ຽວກັບ Anup House ບໍ?', contactText: 'ສຳລັບຂໍ້ມູນທົ່ວໄປ, ຄຳແນະນຳໃນທ້ອງຖິ່ນ ຫຼື ການຊ່ວຍວາງແຜນການມາຮອດ, ກະລຸນາຕິດຕໍ່ຄອບຄົວໂດຍກົງ.', whatsappUs: 'ຕິດຕໍ່ທາງ WhatsApp', footer: 'ເຮືອນພັກຄອບຄົວໃນພຸດທະຄະຍາ, ປະເທດອິນເດຍ.'
  }
});

const languageSwitcher = document.querySelector('.language-switch');
const languageLinks = document.querySelectorAll('[data-language]');
const currentLanguage = document.getElementById('current-language');
const currentLanguageMarker = document.getElementById('current-language-marker');
const languagePaths = {
  en: '/', hi: '/hi/', bo: '/bo/', ja: '/ja/', th: '/th/', vi: '/vi/', ko: '/ko/',
  'zh-CN': '/zh-cn/', 'zh-TW': '/zh-tw/', 'yue-HK': '/yue-hk/', my: '/my/', lo: '/lo/'
};
const pageLanguage = document.documentElement.dataset.language || 'en';
const queryLanguage = new URLSearchParams(window.location.search).get('lang');
if (queryLanguage && languagePaths[queryLanguage] && queryLanguage !== pageLanguage) {
  window.location.replace(`${languagePaths[queryLanguage]}${window.location.hash}`);
}
const defaultLanguage = translations[pageLanguage] ? pageLanguage : 'en';

function setLanguage(language) {
  const selected = translations[language] ? language : 'en';
  document.documentElement.lang = selected;
  document.querySelectorAll('[data-i18n]').forEach((element) => {
    const key = element.dataset.i18n;
    element.textContent = translations[selected][key] || translations.en[key] || element.dataset.defaultText || element.textContent;
  });
  languageLinks.forEach((link) => {
    const active = link.dataset.language === selected;
    active ? link.setAttribute('aria-current', 'page') : link.removeAttribute('aria-current');
    if (active) {
      currentLanguage.textContent = link.lastElementChild.textContent;
      currentLanguageMarker.replaceChildren(link.querySelector('.language-marker').firstChild.cloneNode(true));
    }
  });
  localStorage.setItem('anup-house-language', selected);
}

document.querySelectorAll('[data-i18n]').forEach((element) => { element.dataset.defaultText = element.textContent; });
languageSwitcher.addEventListener('keydown', (event) => {
  if (event.key === 'Escape') {
    languageSwitcher.removeAttribute('open');
    languageSwitcher.querySelector('summary').focus();
  }
});
setLanguage(defaultLanguage);
document.getElementById('year').textContent = new Date().getFullYear();
